name: Maven CI/CD
on:
  push:
    branches:
      - master
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Display Current Directory
        run: pwd
      - name: List Repository Files
        run: ls -la
